spring:
  profiles:
    active: local

---

spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      maximum-pool-size: 30
      max-lifetime: 60000
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
      password:
      connection-timeout: 5000
      pool-name: Spring-HikariPool
  exposed:
    generate-ddl: true

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      maximum-pool-size: 40
      max-lifetime: 60000
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      jdbc-url: jdbc:mysql://localhost:3306/member?serverTimezone=UTC&rewriteBatchedStatements=true
      connection-timeout: 5000
      pool-name: Spring-HikariPool
  exposed:
    generate-ddl: true