spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test_db;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximumPoolSize: 10
