spring:
  application:
    name: embedded_mongo
  data:
    mongodb:
      username: someUser
      password: dontGuess
      database: testdb
      port: 27017


de.flapdoodle.mongodb.embedded.version: 6.0.2
