spring:
  datasource:
    hikari:
      maximum-pool-size: 30
      max-lifetime: 60000
      jdbc-url: jdbc:mysql://localhost:3306/dev?serverTimezone=UTC
      username: sa
      password:
      connection-timeout: 5000
      pool-name: Spring-HikariPool
  jpa:
    database-platform: mysql
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        dialect.storage_engine: innodb
        default_batch_fetch_size: 500
        format_sql: true