spring:
  profiles:
    active: local
  batch:
    job:
      names: ${job.name:NONE}
    jdbc:
      initialize-schema: always
---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:test_db;MODE=MYSQL
      username: sa
      password:
      driver-class-name: org.h2.Driver
      maximumPoolSize: 10
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/spring_batch
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

  batch:
    jdbc:
      initialize-schema: always