server:
  port: 8080

feign:
  client:
    config:
      test-api:
        connect-timeout: 3000
        read-timeout: 4000

spring:
  application:
    name: main-api
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    enabled: true
resilience4j:
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 2
        max-wait-duration: 0
  thread-pool-bulkhead:
    configs:
      default:
        max-thread-pool-size: 2
        core-thread-pool-size: 2
        queue-capacity: 2
        keep-alive-duration: 20ms
  ratelimiter:
    instances:
      test:
        limit-for-period: 5
        limit-refresh-period: 4s
        timeout-duration: 10s
  retry:
    configs:
      default:
        max-attempts: 2 # 2회
        wait-duration: 1000 # 1초
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 10
        ring-buffer-size-in-closed-state: 20 # 닫힌 상태에서의 링비트 버퍼의 크기를 설정, default: 100
        ring-buffer-size-in-half-open-state: 10 # 반열림 상태에서의 링비트 버퍼의 크기 설정: default: 10
        wait-duration-in-open-state: 5s # 열림 상태를 유지하는 시간, 해당 시간이후 반열림 상태로 변경된다.
        failure-rate-threshold: 80 # 실패한 호출에 대한 임계값(백분율 %)으로 이 값을 초과하면 서킷이 열린다
        sliding-window-type: COUNT_BASED
