server:
  port: 8080

feign:
  client:
    config:
      test-api:
        connect-timeout: 3000
        read-timeout: 4000
#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        ringBufferSizeInClosedState: 10 # 닫힌 상태에서의 호출 수로, 서킷을 열어야 할지 결정할 때 사용한다.
#        ringBufferSizeInHalfOpenState: 30 # 반열림 상태에서의 호출 수로, 서킷을 다시 열거나 닫힘 상태로 돌아갈지를 결정할 때 사용 한다.
#        failureRateThreshold: 80 # 실패한 호출에 대한 임계값(백분율)으로 이 값을 초과하면 서킷이 열린다.
#        waitDurationInOpenState: 5s # 열림 상태를 유지하는 시간, 해당 시간이후 반열림 상태로 변경된다.
#        slidingWindowType: COUNT_BASED
#        #        registerHealthIndicator: true # actuator 정보 노출을 위한 설정 -> 현재 없음

spring:
  application:
    name: main-api
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411
    enabled: true
resilience4j:
  bulkhead:
    configs:
      default:
        max-concurrent-calls: 2
        max-wait-duration: 0

  ratelimiter:
    instances:
      test:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 5
