version: "2"

services:
  nexus:
    image: sonatype/nexus3
    container_name: 'nexus3'
    volumes:
      - './nexus-data:/nexus-data'
    ports:
      - "8081:8081"
    environment:
      TZ: "Asia/Seoul"