version: "3"
services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: root
    ports:
      - 3306:3306
  redis:
    image: redis
    ports:
      - 6379:6379
